# Data Exploration with Pandas
<table><tr><td>
<img src="https://resizing.flixster.com/Grjhpv0wcwgi-uhfaC3QM8KFglY=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzdmOWE4MWFiLWVlOWMtNDA4Mi05OTA0LTRiNjMxNTEwMzk1MC5qcGc=" height=300><a href="https://resizing.flixster.com/Grjhpv0wcwgi-uhfaC3QM8KFglY=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzLzdmOWE4MWFiLWVlOWMtNDA4Mi05OTA0LTRiNjMxNTEwMzk1MC5qcGc=">source</a></td><td><img src="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRQCHfe9VV3K3Efxv5PYQ_6NYpB20WkKS1zW21UEUmhW1lalECnbwTH3nwQL8XprEMTUCtPeA" height=300><a href="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRQCHfe9VV3K3Efxv5PYQ_6NYpB20WkKS1zW21UEUmhW1lalECnbwTH3nwQL8XprEMTUCtPeA">source</a></td></tr></table>

In [35]:
# importing the package(s) we want to use
import pandas as pd

### Let's explore the movies data set more! ###
We'll use the `pd.read_csv()` function to read the csv file into a DataFrame.

In [36]:
csvFile = 'https://raw.githubusercontent.com/csbfx/advpy122-data/master/top_movies_2020.csv'

movies = pd.read_csv(csvFile)
movies.head()

                                Title      Gross  Gross (Adjusted)  Year
0                  Gone with the Wind  200852579        1895421694  1939
1  Star Wars: Episode IV - A New Hope  460998507        1668979715  1977
2                  The Sound of Music  159287539        1335086324  1965
3          E.T. the Extra-Terrestrial  435110554        1329174791  1982
4                             Titanic  659363944        1270101626  1997

### Part 1: Initial data exploration

We can examine the contents of the resultant DataFrame using the `head()` and `tail()` commands:

In [37]:
### Take a look at the top 3 values of the file
movies.head(3)

                                Title      Gross  Gross (Adjusted)  Year
0                  Gone with the Wind  200852579        1895421694  1939
1  Star Wars: Episode IV - A New Hope  460998507        1668979715  1977
2                  The Sound of Music  159287539        1335086324  1965

In [38]:
### How about the last 5 values of a the file?
movies.tail(5)

                Title      Gross  Gross (Adjusted)  Year
195            Patton   61749765         373287682  1970
196  Fatal Attraction  156645693         371808159  1987
197        Iron Man 2  312433331         371691971  2010
198          Zootopia  341268248         371109157  2016
199         Liar Liar  181410615         370330510  1997

Use the info() method to get a quick description of the dataframe

In [39]:
### Get a quick summary of the data using the info() method
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Title             200 non-null    object
 1   Gross             200 non-null    int64
 2   Gross (Adjusted)  200 non-null    int64
 3   Year              200 non-null    int64
dtypes: int64(3), object(1)
memory usage: 6.4+ KB

### Part 2: Working to filter different elements

2A: Using iloc and loc to extract specific rows and columns

In [40]:
### Get the first 10 elements (movies) of the second column and convert it into a series with a name
first10_col2 = movies.iloc[:10, 1]
first10_col2.name = "First10_Col2"
first10_col2

0    200852579
1    460998507
2    159287539
3    435110554
4    659363944
5     65500000
6    260758300
7    111721910
8    232906145
9    184925486
Name: First10_Col2, dtype: int64

In [41]:
### Get the names of the first 10 movies and convert it into a series and give it type string
first10_col2_str = first10_col2.astype(str)
first10_col2_str

0    200852579
1    460998507
2    159287539
3    435110554
4    659363944
5     65500000
6    260758300
7    111721910
8    232906145
9    184925486
Name: First10_Col2, dtype: object

In [42]:
### Create a smaller dataframe with last 20 elements and all columns except 'Year'. Give the columns new custom names (your choice).
last20_no_year = movies.tail(20).drop(columns=["Year"]).copy()
last20_no_year.columns = ["Movie", "Gross", "movie income(adj)"]
last20_no_year.head()

                                     Movie      Gross  movie income(adj)
180                Guardians of the Galaxy  333176600          385834112
181                              Furious 7  353007020          384393006
182                    Mission: Impossible  180981856          383664957
183  The Hunger Games: Mockingjay - Part 1  337135885          381611053
184                                Minions  336045770          381492054

2B: Subsetting the dataframe based on conditions

In [43]:
### Create a smaller dataframe with movies made in the year 2000s
movies_2000s = movies[(movies["Year"] >= 2000) & (movies["Year"] <= 2009)].sort_values(by="Year", ascending=True)
movies_2000s.head()

,Title,Gross,Gross (Adjusted),Year
122,How the Grinch Stole Christmas,260044825,450760716,2000
175,Cast Away,233632142,392548654,2000
192,Mission: Impossible II,215409889,374469239,2000
89,The Lord of the Rings: The Fellowship of the Ring,315544750,513470378,2001
127,Shrek,267665011,443112922,2001

In [44]:
### How many movies Gross (use 'Gross (Adjusted)') over 1,500,000,000?
count_over_15b = (movies["Gross (Adjusted)"] > 1_500_000_000).sum()
print(count_over_15b)

2

2C: Customizing the dataframe

In [45]:
### Use DataFrame.columns to change the column name to 'Movie','Gross', 'Gross_adj', and 'Year'
movies2 = movies.copy()
movies2.columns = ["Movie", "Gross", "Gross_adj", "Year"]
movies2.head()

                                Movie      Gross   Gross_adj  Year
0                  Gone with the Wind  200852579  1895421694  1939
1  Star Wars: Episode IV - A New Hope  460998507  1668979715  1977
2                  The Sound of Music  159287539  1335086324  1965
3          E.T. the Extra-Terrestrial  435110554  1329174791  1982
4                             Titanic  659363944  1270101626  1997

In [46]:
### Set the 'Movies' column as the index
movies2_indexed = movies2.set_index("Movie")
movies2_indexed.head()

                                        Gross   Gross_adj  Year
Movie
Gone with the Wind                  200852579  1895421694  1939
Star Wars: Episode IV - A New Hope  460998507  1668979715  1977
The Sound of Music                  159287539  1335086324  1965
E.T. the Extra-Terrestrial          435110554  1329174791  1982
Titanic                             659363944  1270101626  1997

2D: Getting some statistic about the data

In [47]:
### Get some statistical information about the 'Gross' column
movies["Gross"].describe()

count    2.000000e+02
mean     2.564920e+08
std      1.705675e+08
min      9.183673e+06
25%      1.169264e+08
50%      2.341963e+08
75%      3.633033e+08
max      9.366622e+08
Name: Gross, dtype: float64

In [50]:
### What is the average 'Gross (Adjusted)' value for Movies from the 1990s?
avg_gross_adj_1990s = movies2.loc[(movies2["Year"] >= 1990) & (movies2["Year"] <= 1999), "Gross_adj"].mean()
print(avg_gross_adj_1990s)

533060043.13793105

In [49]:
### What is the standard deviation of 'Gross (Adjusted)'?
std_gross_adj = movies2["Gross_adj"].std()
std_gross_adj

227797683.44724277